language: node_js

node_js:
   - node # will use latest node

before_script: # commands to run before the build step
   - npm install -g firebase-tools
   - npm install -g --silent @angular/cli
   - npm install

script: # the build step
   - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN --non-interactive

notifications:
  email: # only receive email when the build status changes (someone broke the build!) 
    on_failure: change
    on_success: change